# Generated by Django 2.1 on 2019-01-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.TextField(max_length='100'),
        ),
        migrations.AlterField(
            model_name='image',
            name='number_views',
            field=models.IntegerField(default=0),
        ),
    ]
